[package]
name = "zilch-ledger2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="zilchmarket2"
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "0.9.2"
solana-program = "1.15.2"
